"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {Phone,Plus,Pencil,Search,Trash2,Wrench} from "lucide-react";
import {WhatsAppIcon} from "@/components/WhatsAppIcon";
import {deleteContact,saveContact} from "./actions";
import {whatsappUrl,type Contact} from "./logic";
import {TOUR_OPERATORS} from "@/features/records/logic/tour-commission";
import type {Locale} from "@/lib/i18n";
const categories={maintenance:["Mantenimiento","Maintenance"],ac:["Aire acondicionado","AC maintenance"],pool:["Piscina","Pool maintenance"],septic:["Sistema séptico","Septic system"],supplies:["Suministros","Supplies"],tour:["Tours","Tours"],other:["Otros","Other"]};
export function ContactDirectory({contacts,locale}:{contacts:Contact[];locale:Locale}) {
 const es=locale==="es", router=useRouter(); const [query,setQuery]=useState(""); const [edit,setEdit]=useState<Contact|null>(null); const [error,setError]=useState(""); const [pending,start]=useTransition(); const [listError,setListError]=useState("");
 const visible=contacts.filter(c=>`${c.name} ${c.category} ${c.phone} ${c.notes}`.toLowerCase().includes(query.toLowerCase()));
 function submit(form:FormData){start(async()=>{const result=await saveContact(form);if(!result.ok){setError(`${es?"No se pudo guardar. Revise el teléfono con código de país y el operador (sin duplicados).":"Could not save. Check the phone including country code and ensure the operator is not duplicated."} (${result.error})`);return;}setEdit(null);setError("");router.refresh();});}
 function remove(c:Contact){if(!window.confirm(`${es?"¿Eliminar este contacto?":"Delete this contact?"}
${c.name}`))return;start(async()=>{const result=await deleteContact(c.id);if(!result.ok){setListError(`${es?"No se pudo eliminar":"Could not delete"} ${c.name}: ${result.error}`);return;}setListError("");router.refresh();});}
 return <><div className="directory-toolbar"><label><Search size={18}/><input aria-label={es?"Buscar proveedores":"Search suppliers"} placeholder={es?"Buscar nombre, servicio o teléfono":"Search name, service or phone"} value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="primary-button" onClick={()=>{setError("");setEdit({id:"",name:"",category:"other",phone:"+506 ",notes:"",operator_name:""});}}><Plus size={18}/>{es?"Añadir contacto":"Add contact"}</button></div>{listError&&<p role="alert" className="form-error">{listError}</p>}<div className="supplier-grid">{visible.map(c=><article className="supplier-card" key={c.id}><header><span className="supplier-avatar"><Wrench size={22}/></span><div><h2>{c.name}</h2><p>{categories[c.category as keyof typeof categories]?.[es?0:1]??c.category}</p></div></header>{c.notes&&<p className="supplier-note">{c.notes}</p>}<div className="supplier-buttons"><a className="whatsapp-button" href={whatsappUrl(c.phone,es?`Hola ${c.name}, le escribimos de Hotel Yuli. `:`Hello ${c.name}, this is Hotel Yuli. `)} target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>WhatsApp · +{c.phone}</a><a className="secondary-button" href={`tel:+${c.phone}`} aria-label={`${es?"Llamar a":"Call"} ${c.name}`}><Phone size={18}/></a></div><div className="supplier-manage"><button type="button" className="secondary-button" aria-label={`${es?"Editar":"Edit"} ${c.name}`} disabled={pending} onClick={()=>{setError("");setEdit(c);}}><Pencil size={15}/>{es?"Editar":"Edit"}</button><button type="button" className="secondary-button danger-button" aria-label={`${es?"Eliminar":"Delete"} ${c.name}`} disabled={pending} onClick={()=>remove(c)}><Trash2 size={15}/>{es?"Eliminar":"Delete"}</button></div></article>)}</div>{!visible.length&&<p>{es?"No hay contactos que coincidan.":"No matching contacts."}</p>}
 {edit&&<div className="modal-backdrop"><section className="team-modal record-modal" role="dialog" aria-modal="true" aria-labelledby="contact-title"><header><h2 id="contact-title">{es?"Contacto del proveedor":"Supplier contact"}</h2><button aria-label={es?"Cerrar":"Close"} onClick={()=>setEdit(null)}>×</button></header><form onSubmit={e=>{e.preventDefault();submit(new FormData(e.currentTarget));}}><input type="hidden" name="id" value={edit.id}/><div className="edit-cell-form"><label>{es?"Nombre":"Name"}<input name="name" defaultValue={edit.name} required maxLength={120}/></label><label>{es?"Servicio":"Service"}<select name="category" value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}>{Object.entries(categories).map(([v,l])=><option key={v} value={v}>{l[es?0:1]}</option>)}</select></label><label>{es?"Teléfono (código de país)":"Phone (country code)"}<input name="phone" type="tel" defaultValue={`+${edit.phone.replace(/^\+/,"")}`} required placeholder="+506 8888 8888"/></label><label>{es?"Notas":"Notes"}<input name="notes" defaultValue={edit.notes} maxLength={500}/></label>{edit.category==="tour"?<label className="full-width">{es?"Operador vinculado (mismo nombre que en la reserva)":"Linked operator (same name as booking)"}<input name="operator_name" defaultValue={edit.operator_name} list="tour-operators" maxLength={120} required/><datalist id="tour-operators">{TOUR_OPERATORS.map(o=><option key={o} value={o}/>)}</datalist></label>:<input type="hidden" name="operator_name" value=""/>}{error&&<p role="alert" className="form-error full-width">{error}</p>}</div><footer><button type="button" className="secondary-button" onClick={()=>setEdit(null)}>{es?"Cancelar":"Cancel"}</button><button className="primary-button" disabled={pending}>{pending?"…":es?"Guardar":"Save"}</button></footer></form></section></div>}</>;
}
